// ============================================================
//  fabric-client.js — Hyperledger Fabric SDK wrapper
//  Handles all communication with the blockchain network
// ============================================================
'use strict';

const { Gateway, Wallets } = require('@hyperledger/fabric-gateway');
const grpc = require('@grpc/grpc-js');
const crypto = require('crypto');
const fs   = require('fs');
const path = require('path');
const logger = require('../config/logger');

// ─────────────────────────────────────────────────────────────
// CONFIGURATION
// ─────────────────────────────────────────────────────────────

const CHANNEL_NAME   = process.env.FABRIC_CHANNEL    || 'otp-channel';
const CHAINCODE_NAME = process.env.FABRIC_CHAINCODE  || 'otp-contract';
const MSP_ID         = process.env.FABRIC_MSP_ID     || 'Org1MSP';
const PEER_ENDPOINT  = process.env.FABRIC_PEER_ENDPOINT || 'localhost:7051';
const PEER_HOST      = PEER_ENDPOINT.split(':')[0];

// Paths to crypto material (generated by Fabric CA)
const CRYPTO_PATH = path.resolve(
  process.env.CRYPTO_PATH ||
  path.join(__dirname, '..', 'crypto-config', 'peerOrganizations', 'org1.otp.com')
);

const TLS_CERT_PATH  = path.join(CRYPTO_PATH, 'peers', 'peer0.org1.otp.com', 'tls', 'ca.crt');
const CERT_PATH      = path.join(CRYPTO_PATH, 'users', 'User1@org1.otp.com', 'msp', 'signcerts');
const KEY_PATH       = path.join(CRYPTO_PATH, 'users', 'User1@org1.otp.com', 'msp', 'keystore');

// ─────────────────────────────────────────────────────────────
// CONNECTION MANAGEMENT
// ─────────────────────────────────────────────────────────────

let gateway = null;
let network = null;
let contract = null;

/**
 * Connect to the Fabric network.
 * Call this once at app startup — reuse the connection for all requests.
 */
async function connectToFabric() {
  try {
    logger.info('Connecting to Hyperledger Fabric network...');

    // Load TLS certificate
    const tlsCert = fs.readFileSync(TLS_CERT_PATH);

    // Create gRPC connection to peer
    const grpcConnection = new grpc.Client(PEER_ENDPOINT, grpc.credentials.createSsl(tlsCert), {
      'grpc.ssl_target_name_override': PEER_HOST,
    });

    // Load user identity credentials
    const certFiles = fs.readdirSync(CERT_PATH);
    const certPem   = fs.readFileSync(path.join(CERT_PATH, certFiles[0]));

    const keyFiles = fs.readdirSync(KEY_PATH);
    const keyPem   = fs.readFileSync(path.join(KEY_PATH, keyFiles[0]));

    // Build identity signer
    const identity = { mspId: MSP_ID, credentials: certPem };
    const signer   = createSigner(keyPem);

    // Create gateway connection
    gateway = new Gateway();
    await gateway.connect(grpcConnection, {
      identity,
      signer,
      tlsCredentials: { rootCertificates: tlsCert },
      evaluateOptions: () => ({ deadline: Date.now() + 5000 }),
      endorseOptions: () => ({ deadline: Date.now() + 15000 }),
      submitOptions: () => ({ deadline: Date.now() + 5000 }),
      commitStatusOptions: () => ({ deadline: Date.now() + 60000 }),
    });

    // Get channel and chaincode
    network = gateway.getNetwork(CHANNEL_NAME);
    contract = network.getContract(CHAINCODE_NAME);

    logger.info(`Connected to Fabric: channel=${CHANNEL_NAME}, chaincode=${CHAINCODE_NAME}`);
    return true;

  } catch (error) {
    logger.error('Failed to connect to Fabric:', error.message);
    throw error;
  }
}

/**
 * Create a signer function from a PEM private key
 */
function createSigner(keyPem) {
  const privateKey = crypto.createPrivateKey(keyPem);
  return async (digest) => {
    const sign = crypto.createSign('sha256');
    sign.update(digest);
    sign.end();
    const signature = sign.sign(privateKey);
    return signature;
  };
}

// ─────────────────────────────────────────────────────────────
// CHAINCODE OPERATIONS
// ─────────────────────────────────────────────────────────────

/**
 * Store an OTP hash on the blockchain.
 * This is a SUBMIT transaction (writes to ledger).
 *
 * @param {string} userId   - User identifier
 * @param {string} otpHash  - SHA-256 hash of the OTP
 * @param {number} expiry   - Unix timestamp when OTP expires
 */
async function storeOTPHash(userId, otpHash, expiry) {
  ensureConnected();
  try {
    const result = await contract.submitTransaction(
      'StoreOTPHash',
      userId,
      otpHash,
      String(expiry)
    );
    logger.info(`OTP hash stored on chain for user: ${userId}`);
    return { success: true, txId: result.toString() };
  } catch (error) {
    logger.error(`storeOTPHash failed for ${userId}:`, error.message);
    throw new Error(`Blockchain write failed: ${error.message}`);
  }
}

/**
 * Verify an OTP hash against the blockchain record.
 * This is a SUBMIT transaction (updates 'used' flag on ledger).
 *
 * @param {string} userId    - User identifier
 * @param {string} inputHash - SHA-256 hash of the submitted OTP
 * @returns {boolean} true if OTP matches and is valid
 */
async function verifyOTPHash(userId, inputHash) {
  ensureConnected();
  try {
    const resultBytes = await contract.submitTransaction(
      'VerifyOTPHash',
      userId,
      inputHash
    );
    const result = resultBytes.toString();
    logger.info(`OTP verification for ${userId}: ${result}`);
    return result === 'true';
  } catch (error) {
    logger.error(`verifyOTPHash failed for ${userId}:`, error.message);
    throw new Error(`Blockchain verification failed: ${error.message}`);
  }
}

/**
 * Get audit trail for a user — read-only, does NOT write to ledger.
 *
 * @param {string} userId - User identifier
 * @returns {Array} Array of audit events
 */
async function getAuditTrail(userId) {
  ensureConnected();
  try {
    const resultBytes = await contract.evaluateTransaction('GetAuditTrail', userId);
    return JSON.parse(resultBytes.toString() || '[]');
  } catch (error) {
    logger.error(`getAuditTrail failed for ${userId}:`, error.message);
    throw new Error(`Failed to fetch audit trail: ${error.message}`);
  }
}

/**
 * Invalidate (revoke) an active OTP — admin action
 */
async function invalidateOTP(userId) {
  ensureConnected();
  try {
    await contract.submitTransaction('InvalidateOTP', userId);
    return { success: true };
  } catch (error) {
    logger.error(`invalidateOTP failed for ${userId}:`, error.message);
    throw new Error(`Invalidation failed: ${error.message}`);
  }
}

// ─────────────────────────────────────────────────────────────
// UTILITIES
// ─────────────────────────────────────────────────────────────

/**
 * Compute SHA-256 hash — same formula must be used on frontend and backend
 * Formula: SHA-256(otp + userId + createdAtTimestamp)
 */
function computeOTPHash(otp, userId, timestamp) {
  return crypto
    .createHash('sha256')
    .update(`${otp}${userId}${timestamp}`)
    .digest('hex');
}

/**
 * Disconnect gracefully (call on process exit)
 */
function disconnect() {
  if (gateway) {
    gateway.close();
    logger.info('Fabric gateway disconnected');
  }
}

function ensureConnected() {
  if (!contract) {
    throw new Error('Fabric client not connected. Call connectToFabric() first.');
  }
}

// Graceful shutdown
process.on('SIGINT',  disconnect);
process.on('SIGTERM', disconnect);

module.exports = {
  connectToFabric,
  storeOTPHash,
  verifyOTPHash,
  getAuditTrail,
  invalidateOTP,
  computeOTPHash,
  disconnect,
};
